import React from 'react'

import { LoginForm } from '@/components/forms'
import { Header } from '@/components/layout'

import styles from '@/components/pages/LoginPage.module.scss'

export function LoginPage(): React.ReactElement {
  return (
    <div className={styles['login-page']}>
      <Header />

      <div className={styles.background}>
        SECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONY
      </div>
      <div className={styles['background-secondary']}>
        SECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONYSECRETSYMPHONY
      </div>

      <div className={`surface ${styles['login-form-container']}`}>
        <h2 className={styles['login-form-heading']}>LOGIN</h2>

        <LoginForm />
      </div>
    </div>
  )
}
